### ISSUE TITLE
Shared library not found

### ISSUE THREAD

**Issue by jagilley** [probcomp/LLaMPPL#5]
Hey all,

I'm trying to run LLaMPPL in a Colab notebook and I'm getting the following error upon following the installation instructions and running an example.

```
Traceback (most recent call last):
  File "/content/LLaMPPL/examples/constraints.py", line 1, in <module>
    import llamppl as llp
  File "/content/LLaMPPL/llamppl/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/content/LLaMPPL/llamppl/llama_cpp.py", line 67, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/content/LLaMPPL/llamppl/llama_cpp.py", line 58, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name 'llama' not found
```

I suspect this is downstream of the `-e` flag in the `pip install` but I haven't been able to fix it.

[Perhaps it's a `scikit-build` issue?](https://groups.google.com/g/comp.lang.python/c/JD1xT8krgM8)

Any thoughts?

**Comment by amazingvince** [comment]
My guess based on what you have said is you need to install llama.cpp. Here: https://github.com/ggerganov/llama.cpp. I have not tried so your mile may vary.

**Comment by jagilley** [comment]
It is, in fact a `scikit-build` issue, and the workaround described [here](https://github.com/scikit-build/scikit-build/issues/740) does not work.

@alex-lew how have you been able to get this repo working on a new machine? Let's say, on a Google Colab instance.

**Comment by alex-lew** [comment]
Hi there, sorry I missed this! @postylem was able to get things set up using

```
conda create -n TEST python=3
conda activate TEST
git clone --recurse-submodules git@github.com:probcomp/LLaMPPL.git
cd LLaMPPL
pip install scikit-build
python setup.py develop
```

Does that work for you?

**Comment by postylem** [comment]
More specifically, on a new machine, the following is what worked for me

1. setup (assumes the machine has gcc installed, else might need `conda install -c conda-forge gcc`)
```python
conda create -n TEST python=3 scikit-build
conda activate TEST
git clone --recurse-submodules git@github.com:probcomp/LLaMPPL.git
cd LLaMPPL
python setup.py develop
```

2. put LLaMA model weights in `LLaMPPL/vendor/llama.cpp/models` dir

3. convert weights as instructed [here](https://github.com/alex-lew/llama.cpp/tree/068a0a9c36f4c3a6e8ec58de569e93d47d5b85a1#prepare-data--run)
```bash
# obtain the original LLaMA model weights and place them in ./models
ls ./models
65B 30B 13B 7B tokenizer_checklist.chk tokenizer.model

# install Python dependencies
python3 -m pip install -r requirements.txt

# convert the 7B model to ggml FP16 format
python3 convert.py models/7B/

# quantize the model to 4-bits (using q4_0 method)
./quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin q4_0
```

Then run an example (when prompted, enter model weights path `vendor/llama.cpp/models/7B/ggml-model-q4_0.bin`)
```python
python examples/infilling.py
```

**Comment by jagilley** [comment]
Confirming that the above method works! Thanks @alex-lew and @postylem, closing this issue.

For posterity, Colab specifically will throw an error attempting to clone submodules over ssh. If anyone is trying to run this from Colab, you'll need to change the .gitmodules file to clone over HTTPS instead.

**Comment by postylem** [comment]
@jagilley 
you can also run ssh-keygen on the Colab machine and then add that key to you GitHub account. I've done that in the past to clone via ssh on Colab.  There's probably others who have written steps out for that ... e.g. found one [here](https://sadiaafrinpurba.github.io/post/how-to-clone-github-private-repositories-from-google-colab/).

**Comment by jagilley** [comment]
@postylem yeah I tried that, but ran into some other problems. Oh well, seems like there's workarounds either way
